version: 2.1

orbs:
  aws-eks: circleci/aws-eks@<<pipeline.parameters.dev-orb-version>>
  aws-cli: circleci/aws-cli@2.0.3
  helm: circleci/helm@1.2.0
  kubernetes: circleci/kubernetes@0.12

parameters:
  run-integration-tests:
    description: An internal flag to prevent integration test from running before a development version has been created.
    type: boolean
    default: false
  dev-orb-version:
    description: >
      The development version of the orb to test.
      This value is automatically adjusted by the "trigger-integration-tests-workflow" job to correspond with the specific version created by the commit and should not be edited.
      A "dev:alpha" version must exist for the initial pipeline run.
    type: string
    default: "dev:alpha"

executors:
  docker-x86-debian:
    docker:
      - image: cimg/base:stable

jobs:
  integration-test-1:
    parameters:
      executor:
        type: executor
    executor: << parameters.executor >>
    steps:
      # - aws-eks/setup
      - run:
          name: Download latest eksctl release
          command: curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
      - run: 
          name: Move extracted binary
          command: sudo mv /tmp/eksctl /usr/local/bin
      - run:
          name: Verify install
          command: sudo eksctl version

workflows:
  integration-and-deploy:
    jobs:
      - integration-test-1:
          context: orb-publisher
          matrix:
            parameters:
              executor: ["docker-x86-debian"]
