version: 2.1

orbs:
  aws-eks: circleci/aws-eks@<<pipeline.parameters.dev-orb-version>>
  aws-cli: circleci/aws-cli@2.0.3
  helm: circleci/helm@1.2.0
  kubernetes: circleci/kubernetes@0.12.1
  orb-tools: circleci/orb-tools@10.1.0
  shellcheck: circleci/shellcheck@2.2.4
  browser-tools: circleci/browser-tools@1.2.3
  bats: circleci/bats@1.0


parameters:
  run-integration-tests:
    description: An internal flag to prevent integration test from running before a development version has been created.
    type: boolean
    default: false
  dev-orb-version:
    description: >
      The development version of the orb to test.
      This value is automatically adjusted by the "trigger-integration-tests-workflow" job to correspond with the specific version created by the commit and should not be edited.
      A "dev:alpha" version must exist for the initial pipeline run.
    type: string
    default: "dev:alpha"

executors:
  docker:
    docker:
      - image: cimg/base:stable
  python:
    docker:
      - image: cimg/python:3.10-browsers

commands:
  cluster-setup-check:
    steps:
      - run:
          name: Check if test env should be set up
          command: |
            if [ "${SKIP_TEST_ENV_CREATION}" = "true" ]
            then
              circleci step halt
            fi
  cluster-teardown-check:
    steps:
      - run:
          name: Check if test env should be destroyed
          command: |
            if [ "${SKIP_TEST_ENV_TEARDOWN}" = "true" ]
            then
              circleci step halt
            fi
  quick-cluster-tests:
    steps:
      - run:
          name: Run some tests on the cluster
          command: |
            kubectl get nodes
            kubectl cluster-info
            kubectl config view
            kubectl config get-contexts
            kubectl get pods --namespace kube-system

jobs:
  test-authenticator:
    parameters:
      executor:
        type: executor
      release-tag:
        type: string
        default: ""
    executor: << parameters.executor >>
    steps:
      - aws-eks/install-aws-iam-authenticator:
          release-tag: << parameters.release-tag >>
      - run:
          name: Test aws-iam-authenticator
          command: |
            aws-iam-authenticator
  integration-test-installs:
    parameters:
      executor:
        type: executor
    executor: << parameters.executor >>
    steps:
      - aws-eks/setup
      - run:
          command: command -v eksctl
      - aws-eks/install-aws-iam-authenticator
      - run:
          name: Test aws-iam-authenticator
          command: command -v aws-iam-authenticator
  setup-cluster:
    parameters:
      executor:
        type: executor
      cluster-name:
        type: string
    executor: << parameters.executor >>
    steps:
      - cluster-setup-check
      - aws-eks/install-aws-iam-authenticator
      - aws-eks/create-cluster:
          cluster-name: << parameters.cluster-name >>
          # tags: name=eksorb,purpose=eksorbtest
      - quick-cluster-tests
  setup-cluster-with-many-params:
    parameters:
      executor:
        type: executor
      cluster-name:
        type: string
      region:
        type: string
        default: ""
      zones:
        type: string
        default: ""
    executor: << parameters.executor >>
    steps:
      - cluster-setup-check
      - aws-eks/install-aws-iam-authenticator
      - aws-eks/create-cluster:
          cluster-name: << parameters.cluster-name >>
          nodegroup-name: "orbtest-ng-1"
          node-type: "t2.large"
          aws-region: << parameters.region >>
          zones: "<< parameters.zones >>"
          nodes: 4
          nodes-min: 3
          nodes-max: 4
          node-volume-size: 30
          node-volume-type: "gp2"
          max-pods-per-node: 30
          node-ami-family: "AmazonLinux2"
          node-private-networking: false
          node-labels: "nodeowner=cci,nodepurpose=testing"
          vpc-cidr: "192.168.0.0/16"
          aws-max-polling-wait-time: "25m"
          tags: "name=cci_orbs,purpose=orb_test"
          verbose: 3
          show-eksctl-command: true
      - quick-cluster-tests
  test-cluster:
    parameters:
      executor:
        type: executor
      region:
        type: string
        default: ""
      cluster-name:
        type: string
    executor: << parameters.executor >>
    steps:
      - checkout
      - kubernetes/install
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      # Test various update-kubeconfig options
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
          aws-region: << parameters.region >>
          dry-run: true
          verbose: true
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
          aws-region: << parameters.region >>
          kubeconfig-file-path: kube-config.test
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
          aws-region: << parameters.region >>
      - quick-cluster-tests
      - run:
          name: Run kubectl proxy
          command: |
            kubectl proxy --port=8080
          background: true
      - run:
          name: Test kube-config and k8s API
          command: |
            cat kube-config.test | grep << parameters.cluster-name >>
            sleep 10
            curl http://localhost:8080/api/
      - kubernetes/create-or-update-resource:
          resource-file-path: "integration-tests/kubernetes-dashboard/kubernetes-dashboard.yaml"
          get-rollout-status: true
          namespace: kube-system
          resource-name: "deployment/kubernetes-dashboard"
      - kubernetes/create-or-update-resource:
          resource-file-path: "integration-tests/kubernetes-dashboard/influxdb-heapster.yaml"
          get-rollout-status: true
          namespace: kube-system
          resource-name: "deployment/heapster"
      - kubernetes/create-or-update-resource:
          resource-file-path: "integration-tests/kubernetes-dashboard/influxdb.yaml"
          get-rollout-status: true
          namespace: kube-system
          resource-name: "deployment/monitoring-influxdb"
      - kubernetes/create-or-update-resource:
          resource-file-path: "integration-tests/kubernetes-dashboard/heapster-rbac.yaml"
      - kubernetes/create-or-update-resource:
          resource-file-path: "integration-tests/kubernetes-dashboard/eks-admin-service-account.yaml"
      - run:
          name: Verify kubernetes dashboard
          command: |
            kubectl get services --namespace=kube-system
            kubectl get pods --namespace=kube-system
            curl -s 'http://localhost:8080/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/#!/login' | grep "kubernetesDashboard"
      - run:
          name: Set up python environment for browser-based test
          command: |
            sudo apt update
            sudo apt install pip
            pip install --upgrade pip
            curl -L -O https://files.pythonhosted.org/packages/ad/24/39cab5fbaf425ff522e1e51cce79f94f10f9523f015d2b2251e43f45e8a2/selenium-4.0.0-py3-none-any.whl
            pip install selenium-4.0.0-py3-none-any.whl
      - run:
          name: Load kubernetes dashboard in browser test
          command: |
            mkdir -p /tmp/artifacts
            cat > test.py \<<-EOF
            import time
            import os
            from selenium import webdriver
            from selenium.webdriver.chrome.service import Service
            s = Service('/usr/local/bin/chromedriver')
            driver = webdriver.Chrome(service=s)
            driver.get('http://localhost:8080/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/#!/login');
            time.sleep(5)
            driver.save_screenshot("/tmp/artifacts/screenshot.png")
            driver.quit()
            EOF
            chmod +x test.py
            python3 test.py
      - store_artifacts:
          path: /tmp/artifacts
  test-update-kubeconfig:
    parameters:
      executor:
        type: executor
      cluster-name:
        type: string
      profile:
        type: string
        default: ""
      region:
        type: string
        default: ""
    executor: << parameters.executor >>
    steps:
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
          aws-profile: << parameters.profile >>
          aws-region: << parameters.region >>
      - run:
          name: Test aws cli
          command: |
            aws configure list
            aws configure list | grep "<< parameters.profile >>"
            aws configure list | grep "<< parameters.region >>"
      - run:
          name: Test aws-iam-authenticator
          command: |
            aws-iam-authenticator
      - kubernetes/install
      - run:
          name: Test with kubectl
          command: |
            cat ~/.kube/config | grep "<< parameters.cluster-name >>"
            kubectl cluster-info
  delete-cluster:
    parameters:
      executor:
        type: executor
      region:
        type: string
        default: ""
      cluster-name:
        type: string
    executor: << parameters.executor >>
    steps:
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
          aws-region: << parameters.region >>
      - cluster-teardown-check
      - aws-eks/delete-cluster:
          cluster-name: << parameters.cluster-name >>
          aws-region: << parameters.region >>
          wait: true
          verbose: 3
          no-output-timeout: 20m
workflows:
  test-pack:
    unless: << pipeline.parameters.run-integration-tests >>
    jobs:
      - orb-tools/lint # Lint Yaml files
      - bats/run:
          path: ./tests
      - orb-tools/pack # Pack orb source
      - shellcheck/check:
          dir: ./src/scripts
          exclude: SC2148, SC1083
      # Publish development version(s) of the orb.
      - orb-tools/publish-dev:
          orb-name: circleci/aws-eks
          context: orb-publisher # A restricted context containing your private publishing credentials. Will only execute if approved by an authorized user.
          requires:
            - orb-tools/lint
            - orb-tools/pack
            - bats/run
            - shellcheck/check
      # Trigger an integration workflow to test the
      # dev:${CIRCLE_SHA1:0:7} version of your orb
      - orb-tools/trigger-integration-tests-workflow:
          name: trigger-integration-dev
          context: orb-publisher
          requires:
            - orb-tools/publish-dev
  integration-and-deploy:
    when: << pipeline.parameters.run-integration-tests >>
    jobs:
      # - integration-test-installs:
      #     context: orb-publisher
      #     matrix:
      #       parameters:
      #         executor: ["docker"]
      # - setup-cluster:
      #     name: setup-cluster-defaults
      #     context: [CPE_ORBS_AWS]
      #     cluster-name: ${AWS_RESOURCE_NAME_PREFIX}-orb-test-defaults
      #     matrix:
      #       parameters:
      #         executor: ["docker"]
      # - test-cluster:
      #     name: test-cluster-defaults
      #     executor: python
      #     context: [CPE_ORBS_AWS]
      #     region: $AWS_DEFAULT_REGION
      #     cluster-name: ${AWS_RESOURCE_NAME_PREFIX}-orb-test-defaults
      #     requires:
      #       - setup-cluster-defaults
      # - test-authenticator:
      #     name: test-authenticator
      #     matrix:
      #       parameters:
      #         executor: ["docker"]
      #     requires:
      #       - setup-cluster-defaults
      # - test-update-kubeconfig:
      #     name: test-update-kubeconfig_region
      #     cluster-name: ${AWS_RESOURCE_NAME_PREFIX}-orb-test-defaults
      #     context: [CPE_ORBS_AWS]
      #     region: $AWS_DEFAULT_REGION
      #     matrix:
      #       parameters:
      #         executor: ["docker"]
      #     requires:
      #       - setup-cluster-defaults
      # - delete-cluster:
      #     name: delete-cluster-defaults
      #     cluster-name: ${AWS_RESOURCE_NAME_PREFIX}-orb-test-defaults
      #     context: [CPE_ORBS_AWS]
      #     matrix:
      #       parameters:
      #         executor: ["docker"]
      #     requires:
      #       - test-cluster-defaults
      - setup-cluster-with-many-params:
          name: setup-cluster-custom-values
          cluster-name: ${AWS_RESOURCE_NAME_PREFIX}-orb-test-custom-values
          context: [CPE_ORBS_AWS]
          region: "us-west-2"
          matrix:
            parameters:
              executor: ["docker"]
          zones: "us-west-2a"
      - test-cluster:
          name: test-cluster-custom-values
          cluster-name: ${AWS_RESOURCE_NAME_PREFIX}-orb-test-custom-values
          context: [CPE_ORBS_AWS]
          region: "us-west-2"
          matrix:
            parameters:
              executor: ["docker"]
          requires:
            - setup-cluster-custom-values
      - delete-cluster:
          name: delete-cluster-custom-values
          cluster-name: ${AWS_RESOURCE_NAME_PREFIX}-orb-test-custom-values
          context: [CPE_ORBS_AWS]
          region: "us-west-2"
          matrix:
            parameters:
              executor: ["docker"]
          requires:
            - test-cluster-custom-values
