description: |
  Allows the stock kubectl client to work with Amazon EKS.
  Installs the AWS CLI, the AWS IAM Authenticator for Kubernetes and
  updates the kubectl configuration file to use the AWS IAM Authenticator.
parameters:
  cluster-name:
    description: |
      The name of the cluster for which to create a kubeconfig entry.
    type: string
  aws-region:
    description: |
      The AWS region that the cluster is in. If not specified, the configured default
      region for your AWS CLI installation will be used.
    type: string
    default: ""
  aws-profile:
    description: |
      The AWS profile to be used. If not specified, the configured default
      profile for your AWS CLI installation will be used.
    type: string
    default: ""
  kubeconfig-file-path:
    description: |
      Specifies a kubeconfig file to append the configuration details to.
      By default, the configuration is written to the first file path in the
      KUBECONFIG environment variable (if it is set) or the default kubeconfig
      path (.kube/config) in your home directory.
    type: string
    default: ""
  cluster-authentication-role-arn:
    description: |
      To assume a role for cluster authentication, specify an IAM role ARN with
      this option. For example, if you created a cluster while assuming an IAM
      role, then you must also assume that role to connect to the cluster the
      first time.
    type: string
    default: ""
  cluster-context-alias:
    description: |
      Alias for the cluster context name. If a value is not specified,
      the cluster context name will be set to match the cluster ARN.
    type: string
    default: ""
  dry-run:
    description: |
      Print the merged kubeconfig to stdout instead of writing it to file.
    type: enum
    default: ""
    enum: [ "", "server", "client" ]
  verbose:
    description: |
      Print more detailed output when writing to the kubeconfig file.
    type: boolean
    default: false
  authenticator-release-tag:
    description: |
      Specifies which release-tag version of the authenticator to install.
    type: string
    default: ""
  install-kubectl:
    description: |
      Whether to install kubectl
    type: boolean
    default: false
  kubectl-version:
    description: |
      Version of kubectl to install
    type: string
    default: "v1.22.0"
  install-aws-cli:
    description: |
      Whether to install aws-cli
    type: boolean
    default: true

steps:
  - when:
      condition: << parameters.install-kubectl >>
      steps:
        - kubernetes/install:
            kubectl-version: << parameters.kubectl-version >>
  - install-aws-iam-authenticator:
      release-tag: << parameters.authenticator-release-tag >>
  - when:
      condition: << parameters.install-aws-cli >>
      steps:
        - aws-cli/setup
  - run:
      environment:
        PARAM_CLUSTER_NAME: << parameters.cluster-name >>
        PARAM_AWS_REGION: << parameters.aws-region >>
        PARAM_AWS_PROFILE: << parameters.aws-profile >>
        PARAM_KUBECONFIG_FILE_PATH: << parameters.kubeconfig-file-path >>
        PARAM_ROLE_ARN: << parameters.cluster-authentication-role-arn >>
        PARAM_CLUSTER_CONTEXT_ALIAS: << parameters.cluster-context-alias >>
        PARAM_DRY_RUN: << parameters.dry-run >>
        PARAM_VERBOSE: << parameters.verbose >>
      name: Update the kubectl configuration file to use the authenticator
      command: <<include(scripts/update-kubeconfig-with-authenticator.sh)>>
