description: |
  Create a kubernetes deployment.
usage:
  version: 2.1

  orbs:
    aws-eks: circleci/aws-eks@<<pipeline.parameters.dev-orb-version>>
    kubernetes: circleci/kubernetes@1.3

  jobs:
    create-deployment:
      docker:
        - image: cimg/python:3.10
      parameters:
        cluster_name:
          description: |
            Name of the EKS cluster
          type: string
      steps:
        - checkout
        - aws-eks/update_kubeconfig_with_authenticator:
            cluster_name: << parameters.cluster_name >>
            install_kubectl: true
        - kubernetes/create-or-update-resource:
            resource-file-path: "tests/nginx-deployment/deployment.yaml"
            resource-name: "deployment/nginx-deployment"
            get-rollout-status: true

  workflows:
    deployment:
      jobs:
        - aws-eks/create_cluster:
            cluster_name: eks-demo-deployment
        - create-deployment:
            cluster_name: eks-demo-deployment
            requires:
              - aws-eks/create_cluster
        - aws-eks/update_container_image:
            cluster_name: eks-demo-deployment
            resource_name: "deployment/nginx-deployment"
            container_image_updates: "nginx=nginx:1.9.1"
            requires:
              - create-deployment
            post-steps:
              - kubernetes/delete-resource:
                  resource-types: "deployment"
                  resource-names: "nginx-deployment"
                  wait: true
        - aws-eks/delete_cluster:
            cluster_name: eks-demo-deployment
            requires:
              - aws-eks/update_container_image
